### ISSUE TITLE
Update source code

### ISSUE THREAD

**Issue by pRieStaKos** [papakigr/GoldResellers-WhmcsModule#1]
Καλησπέρα,

Πρέπει να ανανεώσετε τον κώδικα σε έκδοση WHMCS 6.x (7,x), γιατί λόγω PHP θα γίνουν πολλές functions της deprecated και remove (όπως το _mysql_query()_)

**Comment by voulaTroulaki** [comment]
Καλησπέρα σας,
έχουμε ήδη βάλει στα άμεσα σχέδια μας να κάνουμε τις διορθώσεις που χρειάζονται για τις επόμενες εκδόσεις. 
Θα ενημερωθείτε με νέο commit στο github.

Σας ευχαριστούμε πολύ για την ενημέρωση.

**Comment by voulaTroulaki** [comment]
Καλησπέρα σας,

θα ήθελα να σας ενημερώσω ότι έχουμε κάνει τις απαραίτητες αλλαγές ώστε το papaki.php να χρησιμοποιεί την Capsule για την επικοινωνία με τη βάση

Μπορείτε να κάνετε download από εδώ
https://github.com/papakigr/GoldResellers-WhmcsModule/tree/Php7Changes

Ευχαριστούμε
